### ISSUE TITLE
결과 페이지를 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/turtle-insight#28]
### ✨ Describe

결과 페이지의 디자인을 수정하고 적용하지 못한 기능을 추가 적용합니다.

### ✅ Tasks

- [x] 배경 이미지 바꾸기
- [x] 칵테일 이름, 태그 색상 수정
- [x] FAB 추가
- [x] 다시하기 버튼 추가
- [x] 출처 추가
- [x] 문의 및 광고 제안 글 추가
- [x] 결과 공유 기능 구현
