### ISSUE TITLE
메인 화면 메뉴 버튼의 위치를 수정하고 문의를 위한 문구를 추가합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/turtle-insight#38]
### ✨ Describe

메인 화면 메뉴 버튼의 위치를 시작 버튼 하단으로 수정하고 문의를 위한 문구 페이지 하단에 추가합니다.

### ✅ Tasks

- [ ] 메뉴 버튼 위치 수정
- [ ] 메뉴 버튼 문구 수정
- [ ] 문의를 위한 문구 추가
