### ISSUE TITLE
결과 페이지 표현 방식을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/turtle-insight#52]
### ✨ Describe

결과 저장 로직을 수정해 새로고침되거나 url로 접근했을 때 오류 페이지가 뜨는 문제를 해결합니다.
또한, 폰트와 이미지가 로딩되는 시간을 줄이고 로딩 페이지를 구현합니다.

### ✅ Tasks

- [x] 결과 저장 로직 수정
- [x] 폰트 파일 변경
- [x] 폰트 preload
- [ ] 이미지 로딩 시간 줄이기
