### ISSUE TITLE
페이지의 시작화면을 구현합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/turtle-insight#6]
### ✨ Describe

웹 페이지의 시작 화면을 구현합니다.

### ✅ Tasks

- [x] 배경 화면 이미지 삽입
- [x] 상단 로고 삽입
- [x] 테스트 시작 버튼 추가
- [x] 메뉴판 버튼 추가
